version: 2

models:
  - name: steam_games
    columns:
      - name: appid
        tests:
          - not_null
          - unique
      - name: game_name
        tests:
          - not_null
      - name: playtime_minutes
        tests:
          - not_null

  - name: mal_anime
    columns:
      - name: mal_id
        tests:
          - not_null
          - unique
      - name: title
        tests:
          - not_null

  - name: spotify_top_tracks
    columns:
      - name: track_id
        tests:
          - not_null
      - name: rank
        tests:
          - not_null

  - name: spotify_top_artists
    columns:
      - name: artist_id
        tests:
          - not_null
      - name: rank
        tests:
          - not_null

  - name: spotify_recently_played
    columns:
      - name: played_at
        tests:
          - not_null
          - unique

  - name: goodreads_books
    columns:
      - name: book_id
        tests:
          - not_null
          - unique
      - name: title
        tests:
          - not_null

  - name: mal_manga
    columns:
      - name: mal_id
        tests:
          - not_null
          - unique
      - name: title
        tests:
          - not_null
