version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: steam_owned_games
      - name: steam_profile
      - name: steam_achievements
      - name: mal_anime_list
      - name: mal_manga_list
      - name: goodreads_books
      - name: spotify_top_tracks
      - name: spotify_top_artists
      - name: spotify_recently_played
      - name: github_profile
      - name: github_repos
      - name: x_profile
      - name: x_tweets
