version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: steam_owned_games
      - name: steam_profile
      - name: steam_achievements
      - name: mal_anime_list
      - name: mal_manga_list
